title: "urban grasslands"

plugins:
  - jekyll-timeago
  - jekyll-toc
  - kramdown


theme: jekyll-text-theme
timezone: Europe/Budapest

baseurl: ""
url: "https://marietta.github.io"

jekyll-toc:
  toc_levels: 1..6
  with_front_matter_toc: false

collections:
  species:
    output: true
  taxonomy:
    output: true
  posts:
    output: true
  notes:
    output: true
  tags:
    output: true
  padapt:
    output: true

#page_gen:
#  - data: 'padapt'
#    template: 'padapt'
#    name: 'name'
#    dir: 'padapt'

#  - data: 'padapt'
#    template: 'taxonomy'
#    name: 'order_lat'
#    dir: 'taxonomy'
#  - data: 'padapt'
#    template: 'taxonomy'
#    name: 'genus_lat'
#    dir: 'taxonomy'


defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cover.png


